### ISSUE TITLE
Finish Plugin Interface

### ISSUE THREAD

**Issue by octalmage** [octalmage/mDesktop#18]
## Introduction

Currently there is a very basic API implemented using [WM_COPYDATA](http://msdn.microsoft.com/en-us/library/ms649011%28v=vs.85%29.aspx). Extend this to support registering plugins and bidirectional data. 
## Tasks
- [ ] Add support for installing plugins. 
  - Plugins will be installed in the plugins subdirectory.
  - The plugin package will either include an .ini file with details about the API window, or we will assume it's the same as the .exe filename. 
  - Either allow the plugin to subscribe to messages using the .ini, or send all messages to each plugin. Currently I'm leaning towards sending all messages.  
- [ ] Send each plugin their subscribed messages. 
  - Desktop changed.
- [ ] Implement additional methods. 
  - Send window to desktop.
  - Get list of windows on desktop.
##
